export const COMPANY_LOAD_START   = 'COMPANY_LOAD_START';
export const COMPANY_LOAD_SUCCESS = 'COMPANY_LOAD_SUCCESS';
export const COMPANY_LOAD_FAIL    = 'COMPANY_LOAD_FAIL';

export const VIEW_FORM_ADD_COMPANY_SET_TRUE  = 'VIEW_FORM_ADD_COMPANY_SET_TRUE';
export const VIEW_FORM_ADD_COMPANY_SET_FALSE = 'VIEW_FORM_ADD_COMPANY_SET_FALSE';
export const VIEW_FORM_ADD_COMPANY_FAIL      = 'VIEW_FORM_ADD_COMPANY_FAIL';

export const SIGNUP_START   = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL    = 'SIGNUP_FAIL';

export const COMPANY_ADD_NEW_AID_START   = 'COMPANY_ADD_NEW_AID_START';
export const COMPANY_ADD_NEW_AID_SUCCESS = 'COMPANY_ADD_NEW_AID_SUCCESS';
export const COMPANY_ADD_NEW_AID_FAIL    = 'COMPANY_ADD_NEW_AID_FAIL';

export const COMPANY_PATCH_START   = 'COMPANY_PATCH_START';
export const COMPANY_PATCH_FAIL    = 'COMPANY_PATCH_FAIL';
export const COMPANY_PATCH_SUCCESS = 'COMPANY_PATCH_SUCCESS';

export const COMPANY_DELETE_START   = 'COMPANY_DELETE_START';
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS';
export const COMPANY_DELETE_FAIL    = 'COMPANY_DELETE_FAIL';

export const GET_TYPES_COMPANY_START   = 'GET_TYPES_COMPANY_START';
export const GET_TYPES_COMPANY_SUCCESS = 'GET_TYPES_COMPANY_SUCCESS';
export const GET_TYPES_COMPANY_FAIL    = 'GET_TYPES_COMPANY_FAIL';