# Generated by Django 3.0.4 on 2020-03-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('short_title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=2000)),
                ('date_public', models.DateField()),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=2)),
                ('serial_number', models.PositiveIntegerField()),
                ('eula', models.FileField(upload_to='license')),
                ('cost', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('status_id', models.CharField(choices=[('ok', 'Успешно'), ('err', 'Ошибка'), ('wait', 'Обработка')], max_length=50)),
            ],
            options={
                'verbose_name': 'Электронное обучающее пособие',
                'verbose_name_plural': 'Электронные обучающие пособия',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='Название организации')),
                ('location', models.CharField(max_length=400, verbose_name='Город организации')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта организации')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работник',
            },
        ),
        migrations.CreateModel(
            name='status_aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование статуса')),
            ],
            options={
                'verbose_name': 'Статусы ЭОП',
                'verbose_name_plural': 'Статус ЭОП',
            },
        ),
        migrations.CreateModel(
            name='type_aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа ЭОП')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Типы ЭОП',
                'verbose_name_plural': 'Тип ЭОП',
            },
        ),
        migrations.CreateModel(
            name='type_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Типы компаний',
                'verbose_name_plural': 'Тип компании',
            },
        ),
        migrations.CreateModel(
            name='type_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название операции')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое название операции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('key', models.PositiveSmallIntegerField(verbose_name='Ключ операции')),
            ],
            options={
                'verbose_name': 'Типы операций',
                'verbose_name_plural': 'Тип операции',
            },
        ),
        migrations.CreateModel(
            name='type_storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя типа')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Типы хранилищ',
                'verbose_name_plural': 'Тип хранилища',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('Identifying_number', models.UUIDField(verbose_name='Идентификационный номер')),
                ('ip', models.GenericIPAddressField(verbose_name='ipv4')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.type_storage')),
            ],
            options={
                'verbose_name': 'Хранилище',
                'verbose_name_plural': 'Хранилища',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('err', 'Ошибка'), ('wait', 'Обработка')], max_length=50)),
                ('aid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aid', verbose_name='id ЭОП')),
                ('employer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Employer')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.type_aid')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.CreateModel(
            name='Employer_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Company')),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работники компаний',
                'verbose_name_plural': 'Работник компании',
            },
        ),
        migrations.CreateModel(
            name='company_aids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appeal', models.DateField(auto_now=True)),
                ('aids_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Aid')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Company')),
                ('emp_company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Employer_company')),
            ],
            options={
                'verbose_name': 'Список ЭОП компаний',
                'verbose_name_plural': 'ЭОП компании',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.type_company'),
        ),
        migrations.AddField(
            model_name='aid',
            name='employer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Employer'),
        ),
        migrations.AddField(
            model_name='aid',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.type_aid'),
        ),
    ]
