# Generated by Django 3.0.4 on 2020-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200328_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='date_public',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='eula',
            field=models.FileField(null=True, upload_to='license'),
        ),
    ]
