# Generated by Django 3.0.4 on 2020-04-03 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200330_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='type_aid',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='type_operation',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='type_storage',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
