# Generated by Django 3.0.4 on 2020-04-03 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200403_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='serial_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
