# Generated by Django 3.0.4 on 2020-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200403_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='status_id',
            field=models.CharField(choices=[('ok', 'Успешно'), ('err', 'Ошибка'), ('wait', 'Обработка')], default='wait', max_length=50),
        ),
    ]
