# Generated by Django 3.0.4 on 2020-04-03 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200403_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='eula',
            field=models.FileField(blank=True, null=True, upload_to='license'),
        ),
        migrations.AlterField(
            model_name='aid',
            name='language',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='aid',
            name='serial_number',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
