# Generated by Django 3.0.4 on 2020-04-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200404_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='eula',
            field=models.FileField(blank=True, null=True, upload_to='license/'),
        ),
    ]
