# Generated by Django 3.0.4 on 2020-04-11 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200406_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='Identifying_number',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Идентификационный номер'),
        ),
    ]
