# Generated by Django 3.0.4 on 2020-04-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200411_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='Identifying_number',
            new_name='identifying_number',
        ),
        migrations.AddField(
            model_name='aid',
            name='storage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Storage'),
        ),
    ]
