# Generated by Django 3.0.4 on 2020-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200411_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Выключен'), (1, 'Включен')], default=0, verbose_name='Состояние включенности'),
        ),
    ]
