# Generated by Django 3.0.4 on 2020-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200415_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='key_words',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='aid',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='aid',
            name='source',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='aid',
            name='type_access',
            field=models.CharField(choices=[('free', 'Бесплатное'), ('buy', 'Платное'), ('demo', 'Демо')], default='free', max_length=200),
        ),
        migrations.AddField(
            model_name='aid',
            name='type_divice',
            field=models.CharField(choices=[('phone', 'Телефон'), ('pc', 'ПК'), ('tablet', 'Планшет'), ('phoneAndTablet', 'Телефон и планшет'), ('phoneAndPc', 'Телефон и ПК'), ('pcAndTablet', 'Планшет и ПК'), ('all', 'Все')], default='all', max_length=200),
        ),
    ]
