# Generated by Django 3.0.4 on 2020-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aid_additional_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='additional_req',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
