# Generated by Django 3.0.4 on 2020-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200418_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aid',
            name='type_device',
            field=models.CharField(choices=[('Phone', 'Телефон'), ('Pc', 'ПК'), ('Tablet', 'Планшет'), ('PhoneTablet', 'Телефон и планшет'), ('PhonePc', 'Телефон и ПК'), ('PhoneTabletPC', 'Все')], default='all', max_length=200),
        ),
    ]
