# Generated by Django 3.0.4 on 2020-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200418_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='aid',
            name='media',
            field=models.CharField(choices=[('Photo', 'Фото'), ('Video', 'Видео'), ('Flash', 'Флеш'), ('Other', 'Другое'), ('All', 'Смешанное')], default='free', max_length=200),
        ),
        migrations.AlterField(
            model_name='aid',
            name='key_words',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='aid',
            name='publisher',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
