# Generated by Django 3.0.4 on 2020-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200418_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aid',
            name='source',
        ),
        migrations.AlterField(
            model_name='aid',
            name='key_words',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='aid',
            name='media',
            field=models.CharField(choices=[('Photo', 'Фото'), ('Video', 'Видео'), ('Flash', 'Флеш'), ('Other', 'Другое'), ('All', 'Смешанное'), ('PhotoVideo', 'Фото и видео'), ('PhotoFlash', 'Фото и флеш'), ('PhotoOther', 'Фото и другое'), ('VideoFlash', 'Видео и флеш'), ('VideoOther', 'Видео и другое'), ('FlashOther', 'Флеш и другое'), ('PhotoVideoOther', 'Фото, видео и другое'), ('PhotoFlashOther', 'Фото, флеш и другое'), ('PhotoVideoFlashOther', 'Фото, видео, флеш и другое')], default='All', max_length=200),
        ),
        migrations.AlterField(
            model_name='aid',
            name='type_device',
            field=models.CharField(choices=[('Phone', 'Телефон'), ('Pc', 'ПК'), ('Tablet', 'Планшет'), ('PhoneTablet', 'Телефон и планшет'), ('PhonePc', 'Телефон и ПК'), ('PhoneTabletPc', 'Все гаджеты')], default='PhoneTabletPc', max_length=200),
        ),
    ]
