export const EMPLOYER_LOAD_START   = 'EMPLOYER_LOAD_START';
export const EMPLOYER_LOAD_SUCCESS = 'EMPLOYER_LOAD_SUCCESS';
export const EMPLOYER_LOAD_FAIL    = 'EMPLOYER_LOAD_FAIL';

export const VIEW_FORM_ADD_EMPLOYER_SET_TRUE  = 'VIEW_FORM_ADD_EMPLOYER_SET_TRUE';
export const VIEW_FORM_ADD_EMPLOYER_SET_FALSE = 'VIEW_FORM_ADD_EMPLOYER_SET_FALSE';
export const VIEW_FORM_ADD_EMPLOYER_FAIL      = 'VIEW_FORM_ADD_EMPLOYER_FAIL';

export const ADD_NEW_EMPLOYER_START   = 'ADD_NEW_EMPLOYER_START';
export const ADD_NEW_EMPLOYER_SUCCESS = 'ADD_NEW_EMPLOYER_SUCCESS';
export const ADD_NEW_EMPLOYER_FAIL    = 'ADD_NEW_EMPLOYER_FAIL';

export const EMPLOYER_LOAD_AID_LIST_START   = 'EMPLOYER_LOAD_AID_LIST_START';
export const EMPLOYER_LOAD_AID_LIST_SUCCESS = 'EMPLOYER_LOAD_AID_LIST_SUCCESS';
export const EMPLOYER_LOAD_AID_LIST_FAIL    = 'EMPLOYER_LOAD_AID_LIST_FAIL';

export const EMPLOYER_PATCH_START   = 'EMPLOYER_PATCH_START';
export const EMPLOYER_PATCH_FAIL    = 'EMPLOYER_PATCH_FAIL';
export const EMPLOYER_PATCH_SUCCESS = 'EMPLOYER_PATCH_SUCCESS';

export const EMPLOYER_DELETE_START   = 'EMPLOYER_DELETE_START';
export const EMPLOYER_DELETE_SUCCESS = 'EMPLOYER_DELETE_SUCCESS';
export const EMPLOYER_DELETE_FAIL    = 'EMPLOYER_DELETE_FAIL';
