export const STORAGE_LOAD_START   = 'STORAGE_LOAD_START';
export const STORAGE_LOAD_SUCCESS = 'STORAGE_LOAD_SUCCESS';
export const STORAGE_LOAD_FAIL    = 'STORAGE_LOAD_FAIL';

export const VIEW_FORM_ADD_STORAGE_SET_TRUE  = 'VIEW_FORM_ADD_STORAGE_SET_TRUE';
export const VIEW_FORM_ADD_STORAGE_SET_FALSE = 'VIEW_FORM_ADD_STORAGE_SET_FALSE';
export const VIEW_FORM_ADD_STORAGE_FAIL      = 'VIEW_FORM_ADD_STORAGE_FAIL';

export const ADD_NEW_STORAGE_START   = 'ADD_NEW_STORAGE_START';
export const ADD_NEW_STORAGE_SUCCESS = 'ADD_NEW_STORAGE_SUCCESS';
export const ADD_NEW_STORAGE_FAIL    = 'ADD_NEW_STORAGE_FAIL';

export const STORAGE_LOAD_AID_LIST_START   = 'STORAGE_LOAD_AID_LIST_START';
export const STORAGE_LOAD_AID_LIST_SUCCESS = 'STORAGE_LOAD_AID_LIST_SUCCESS';
export const STORAGE_LOAD_AID_LIST_FAIL    = 'STORAGE_LOAD_AID_LIST_FAIL';

export const STORAGE_PATCH_START   = 'STORAGE_PATCH_START';
export const STORAGE_PATCH_FAIL    = 'STORAGE_PATCH_FAIL';
export const STORAGE_PATCH_SUCCESS = 'STORAGE_PATCH_SUCCESS';

export const STORAGE_DELETE_START   = 'STORAGE_DELETE_START';
export const STORAGE_DELETE_SUCCESS = 'STORAGE_DELETE_SUCCESS';
export const STORAGE_DELETE_FAIL    = 'STORAGE_DELETE_FAIL';

export const GET_TYPES_STORAGE_START   = 'GET_TYPES_STORAGE_START';
export const GET_TYPES_STORAGE_SUCCESS = 'GET_TYPES_STORAGE_SUCCESS';
export const GET_TYPES_STORAGE_FAIL    = 'GET_TYPES_STORAGE_FAIL';