export const AID_LOAD_START   = 'AID_LOAD_START';
export const AID_LOAD_FAIL    = 'AID_LOAD_FAIL';
export const AID_LOAD_SUCCESS = 'AID_LOAD_SUCCESS';

export const VIEW_FORM_ADD_AID_SET_TRUE  = 'VIEW_FORM_ADD_AID_SET_TRUE';
export const VIEW_FORM_ADD_AID_SET_FALSE = 'VIEW_FORM_ADD_AID_SET_FALSE';
export const VIEW_FORM_ADD_AID_FAIL      = 'VIEW_FORM_ADD_AID_FAIL';

export const GET_TYPES_AID_START   = 'GET_TYPES_AID_START';
export const GET_TYPES_AID_SUCCESS = 'GET_TYPES_AID_SUCCESS';
export const GET_TYPES_AID_FAIL    = 'GET_TYPES_AID_FAIL';

export const AID_DELETE_START   = 'AID_DELETE_START';
export const AID_DELETE_SUCCESS = 'AID_DELETE_SUCCESS';
export const AID_DELETE_FAIL    = 'AID_DELETE_FAIL';

export const AID_ADD_START   = 'AID_ADD_START';
export const AID_ADD_SUCCESS = 'AID_ADD_SUCCESS';
export const AID_ADD_FAIL    = 'AID_ADD_FAIL';

export const AID_LOAD_DETAILS_START   = 'AID_LOAD_DETAILS_START';
export const AID_LOAD_DETAILS_FAIL    = 'AID_LOAD_DETAILS_FAIL';
export const AID_LOAD_DETAILS_SUCCESS = 'AID_LOAD_DETAILS_SUCCESS';

export const AID_PATCH_START   = 'AID_PATCH_START';
export const AID_PATCH_FAIL    = 'AID_PATCH_FAIL';
export const AID_PATCH_SUCCESS = 'AID_PATCH_SUCCESS';